### ISSUE TITLE
DatePicker Java 8 Enabled

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces-showcase#123]
@mertsincan The showcase is deployed with Java util.date for DatePicker only.  I htink now that 8.0 is released we need to have the Java 8 Time page enabled too on the showcase for Calendar and Datepicker.

**Comment by christophs78** [comment]
IMO both is deployed
![grafik](https://user-images.githubusercontent.com/10461942/76061932-e6292780-5f84-11ea-852f-9eb69b7b6576.png)

Personally i´ll prefer to default (comming from the menu) to datePickerJava8.xhtml instead of datePicker.xhtml. (Same for Calendar.)
