### ISSUE TITLE
MVN Package step failed due to missing dependency

### ISSUE THREAD

**Issue by brooksie** [primefaces/primefaces-showcase#131]
Getting the following error when I execute "mvn package" command:
[ERROR] Failed to execute goal on project showcase: Could not resolve dependencies for project org.primefaces:showcase:war:9.0-SNAPSHOT: Failure to find org.primefaces:primefaces:jar:9.0-SNAPSHOT in http://repository.primefaces.org was cached in the local repository, resolution will not be reattempted until the update interval of prime-repo has elapsed or updates are forced -> [Help 1]

**Comment by melloware** [comment]
Yep you have to build PrimeFaces 9.0-SNAPSHOT first using "mvn clean install" on the PrimeFaces code.

or edit the pom.xml locally and change every 9.0-SNAPSHOT to 8.0
