### ISSUE TITLE
JDK11: Error running showcase

### ISSUE THREAD

**Issue by markusg80** [primefaces/primefaces-showcase#135]
I like to anaylse primefaces problem and i try to compile and run showcase project. So i first prepared the 9.0-SNAPSHOT project and then i can build the showcase and run it with jetty. But when i use the jetty project and i press the button i get an error: java.lang.ClassNotFoundException: javax.xml.bind.JAXBContext.

**Comment by melloware** [comment]
You are using JDK11+ right?

We set the showcase to run on JDK8.  You will need to add this dependency.
```xml
<dependency>
       <groupId>javax.xml.bind</groupId>
       <artifactId>jaxb-api</artifactId>
       <version>2.3.0</version>
    </dependency>
<dependency>
  <groupId>com.sun.xml.bind</groupId>
  <artifactId>jaxb-core</artifactId>
  <version>2.3.0</version>
</dependency>
<dependency>
  <groupId>com.sun.xml.bind</groupId>
  <artifactId>jaxb-impl</artifactId>
  <version>2.3.0</version>
</dependency>
<dependency>
    <groupId>com.sun.activation</groupId>
    <artifactId>javax.activation</artifactId>
    <version>1.2.0</version>
</dependency>
```

**Comment by tandraschko** [comment]
I think we should add an profile, which automatically activates on jdk11+, which imports jaxb

**Comment by melloware** [comment]
Agreed. I will add one.

**Comment by tandraschko** [comment]
`        <profile>
            <id>java11</id>
            <properties>
                <java.version>8</java.version> 
				<lombok.version>1.18.8</lombok.version>
            </properties>
            <activation>
                <jdk>11</jdk>
            </activation>
            <dependencies>
                <dependency>
                    <groupId>javax.xml.bind</groupId>
                    <artifactId>jaxb-api</artifactId>
                    <version>2.3.0</version>
                </dependency>
                <dependency>
                    <groupId>com.sun.xml.bind</groupId>
                    <artifactId>jaxb-core</artifactId>
                    <version>2.3.0</version>
                </dependency>
                <dependency>
                    <groupId>com.sun.xml.bind</groupId>
                    <artifactId>jaxb-impl</artifactId>
                    <version>2.3.0</version>
                </dependency>
                <dependency>
                    <groupId>com.sun.xml.ws</groupId>
                    <artifactId>jaxws-ri</artifactId>
                    <version>2.3.2</version>
                    <type>pom</type>
                </dependency>
            </dependencies>
        </profile>`

**Comment by tandraschko** [comment]
something like to should work ;)

**Comment by markusg80** [comment]
Oh no i‘m so stupid! I had the same issue when i migrate my project to jdk 11. And yes it would be great to have an maven profile for jdk11. Another thing: First i take a try to compile the showcase with netbeans 11.3. But with the bundled maven verdion the compile failed so i installed maven 3.6.3. So it would be great to state somewhere the minimal maven Version
