### ISSUE TITLE
Error on `mvn clean` & `mvn package`

### ISSUE THREAD

**Issue by alirezameftahi71** [primefaces/primefaces-showcase#173]
when I run either one of these commands: 
`mvn clean install`
`mvn package`

I get the following error:
(this error is the result of running `mvn clean install` but for the other commands it give a similar error about nexus not existing.)
`
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.545 s
[INFO] Finished at: 2020-07-09T09:52:07+04:30
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "nexus" could not be activated because it does not exist.
[ERROR] Failed to execute goal on project showcase: Could not resolve dependencies for project org.primefaces:showcase:war:9.0-SNAPSHOT: The following artifacts could not be resolved: org.primefaces.themes:all-themes:jar:1.0.10, net.sf.barcode4j:barcode4j-light:jar:2.1, org.primefaces:primefaces:jar:9.0-SNAPSHOT: Failure to find org.primefaces.themes:all-themes:jar:1.0.10 in http://192.168.128.193:8081/nexus/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of nexus-lct has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
`

If I run `mvn clean` I get a warning about nexus not being existed, but then when I run `mvn package` I still get the above error anyways.

What am I missing?

UPDATE 01:
I changed every `9.0-SNAPSHOT` to `8.0-SNAPSHOT` but I still get the same error.
UPDATE 02:
I changed them to `8.0` and omitted the `-SNAPSHOT` and still no progress.

**Comment by melloware** [comment]
It looks like an error reaching the internet it looks like you have a Nexus server in bewteen at http://192.168.128.193:8081 and this pom.xml is meant to be pointed at Maven Central.  Do you have a proxy or Nexus configured in your /.m2/settings.xml or something?

**Comment by alirezameftahi71** [comment]
You were right, that was the issue. I had nexus configured in /usr/share/maven/conf/settings.xml
I commented it out and I could run the commands successfully. 
Thank you for the help.
