### ISSUE TITLE
Error running mvn clean jetty:run -JDK 11

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [primefaces/primefaces-showcase#178]
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/git/primefaces-showcase/src/main/java/org/primefaces/showcase/view/data/ScheduleJava8View.java:[118,33] cannot find symbol
  symbol:   method resizable(boolean)
  location: class org.primefaces.model.DefaultScheduleEvent.Builder
[ERROR] /C:/git/primefaces-showcase/src/main/java/org/primefaces/showcase/view/data/ScheduleJava8View.java:[127,33] cannot find symbol
  symbol:   method draggable(boolean)
  location: class org.primefaces.model.DefaultScheduleEvent.Builder

**Comment by melloware** [comment]
You have to build the latest PF 9.0-SNAPSHOT as well?  I am having no problems locally?

I am having no problem running Java 8 or Java 11 and the showcase?
