### ISSUE TITLE
Failure to find org.primefaces:primefaces:jar:9.0-SNAPSHOT

### ISSUE THREAD

**Issue by johbor** [primefaces/primefaces-showcase#223]
In the README.md there is:
git clone https://github.com/primefaces/showcase-facelift.git
cd showcase-facelift
mvn clean                  -- clean temp files from target folder
mvn package                -- create war file (under target directory)
mvn jetty:run              -- run showcase project locally

But mvn package shows an error due to dependencies.
![Screen Shot 2020-11-16 at 21 50 20](https://user-images.githubusercontent.com/9353297/99307435-cad22400-2856-11eb-938a-4c650ed03ecb.png)

**Comment by melloware** [comment]
Yep you have to git clone PrimeFaces first and build that: https://github.com/primefaces/primefaces
