### ISSUE TITLE
SelectOneMenu: RTL Broken in new PrimeOne themes

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces-showcase#242]
**Nova Light:**
![image](https://user-images.githubusercontent.com/4399574/103176275-66838680-483e-11eb-929b-a16b256559a5.png)

**Saga:**
![image](https://user-images.githubusercontent.com/4399574/103176285-756a3900-483e-11eb-8b43-a5a22ae710dc.png)

**Comment by mertsincan** [comment]
I think this issue has been fixed with RC1. For now, close ;)

**Comment by melloware** [comment]
Confirmed fixed!
