### ISSUE TITLE
Buttons are "glued" together in PrimeOne themes

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces-showcase#248]
e.g. /ui/input/datepicker/datePickerJava8.xhtml?jfwid=56e01

![grafik](https://user-images.githubusercontent.com/10461942/103287632-45a86600-49e3-11eb-87a8-74340afc244f.png)

IMO this is a issue with all PrimeOne-based designs. 
nova-light came with margin-right to address this
![grafik](https://user-images.githubusercontent.com/10461942/103287794-b0f23800-49e3-11eb-93e8-f06000fc4eb8.png)

**Comment by melloware** [comment]
Yep report any of these so we can gather them up.  I reported this one: https://github.com/primefaces/primefaces-showcase/issues/242

Hopefully once we get the committers Discord channel we can make sure these Premium Theme issues get addressed before go live.

**Comment by melloware** [comment]
This has been fixed
