### ISSUE TITLE
Radio/Checkbox: Missing ui-state-error in Premium/PrimeOne themes

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces-showcase#253]
If you have a validation error on 'SelectBooleanCheckbox` or `SelectOneRadio` the `ui-state-error` is missing in the CSS for these two components in both Premium Themes and new Primeone Themes.

You can see in the below example the Ajax checkbox has `ui-state-error` but there is no style applied by the Theme.

Example:
![image](https://user-images.githubusercontent.com/4399574/103296352-ea1ab000-49c3-11eb-903d-a34d7d624e01.png)

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primefaces/issues/6888
