### ISSUE TITLE
Schedule: unnecessary disabled scrollbars (week- and day-view)

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces-showcase#254]
e.g. /ui/data/schedule/basic.xhtml
![image](https://user-images.githubusercontent.com/10461942/103300840-25d36b00-4a00-11eb-9533-73dab994064b.png)

Issue may depend on surrounding markup.  (/ui/data/schedule/configureable.xhtml does not seem to have this issue)
Happens with Edge/Chrome and Firefox.

**Comment by melloware** [comment]
I think its related to this ticket which I fixed: https://github.com/primefaces/primefaces/issues/6451

"Adding new height attribute to calenda so you can use auto if you want no scrollbars or a fixed CSS size like 333px or 100%"

**Comment by christophs78** [comment]
Hm. https://fullcalendar.io/ has this issue too.
![image](https://user-images.githubusercontent.com/10461942/103307099-8c13ba00-4a0f-11eb-8ecc-4edc1fc26b51.png)
I have to look into the fullcalendar-github-issues.

Looks like FullCalendar 4 did not have this issue:
http://primefaces.org/showcase/ui/data/schedule/basic.xhtml

**Comment by christophs78** [comment]
Opened following Full Calendar - GitHub-issue - let´s look what they say:
https://github.com/fullcalendar/fullcalendar/issues/6047

**Comment by melloware** [comment]
@christophs78 I will close this for now as it seems like its a 3rd party full calendar issue.
