### ISSUE TITLE
Checkbox: PrimeOne focus styling breaks checkbox

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces-showcase#258]
A picture is worth a thousand words. So let me show you (or you can reproduce on showcase)
![selection](https://user-images.githubusercontent.com/7521311/103317882-e3745300-4a2c-11eb-90f6-e413e985199a.gif)

In 2 words, checkbox selection is not fully checked on first click. My best assumption _(and I can be completely wrong)_ is that, this problem came with the new themes (I don't recall this problem showing before) but it seems to be a mishmash with js and css

**Environment:**
 - PF Version: 9.0-SNAPSHOT
 - Affected browsers: Chrome, Edge

**To Reproduce**
1. Go to http://localhost:8080/showcase/ui/data/datatable/selection.xhtml
2. Checkbox selection
3. Click on checkbox
4. See weird behavior

**Expected behavior**
Just the usual selection 😅 

@Rapster

**Comment by melloware** [comment]
I have debugged the issue above and its because in the PrimeOne themes the `.ui-chkbox-box.ui-state-focus` style is hiding the checkmark while its checked.

![image](https://user-images.githubusercontent.com/4399574/103353271-72598d80-4a76-11eb-8c79-78cb76f19f25.png)

**Comment by melloware** [comment]
Reported by another user: https://github.com/primefaces/primefaces/issues/6834

**Comment by mertsincan** [comment]
@melloware Could you please test it again? It works fine for me.

Thank a lot!

**Comment by melloware** [comment]
@mertsincan its better but something is still not quite right.  If you go to Datatable->Selection example in showcase.

1. Click the row the checkbox highlights correctly.
2. Click the checkbox itself and the checkbox chcecks but is not filled in.
![image](https://user-images.githubusercontent.com/4399574/105176279-0c9b7700-5af3-11eb-85bc-a461c2385779.png)

**Comment by mertsincan** [comment]
This issue is related to ui-state-focus. PrimeFaces core removes ui-state-active on focus and adds ui-state-focus. I think it is by design. Maybe, we can talk about this on the discord channel. For now, close ;)
