### ISSUE TITLE
remove "since vX.Y.Z" - remarks?

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces-showcase#260]
What do you think about removing old "since vX.Y.Z" - remarks?
![image](https://user-images.githubusercontent.com/10461942/103365757-1700bd00-4ac1-11eb-8593-78cb7650d60d.png)

Most of them point back to version 6 which is quite old.

**Comment by melloware** [comment]
Closing this one as lit looks like you opened two of them,
