### ISSUE TITLE
Remove old "since vX.Y.Z" - remarks?

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces-showcase#261]
What do you think about removing old "since vX.Y.Z" - remarks?
![image](https://user-images.githubusercontent.com/10461942/103365757-1700bd00-4ac1-11eb-8593-78cb7650d60d.png)

Most of them point back to version 6 which is quite old.

**Comment by sqores** [comment]
https://github.com/primefaces/primefaces-showcase/commit/eaaf28a7066e0bb58e309edf6cf48b77e82feb81 I removed them.
