### ISSUE TITLE
add component-search functionality

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces-showcase#264]
I know this is not specific to PrimeFaces.... It´s the same for alle PrimeNG-Showcase and PrimeVue-Showcase. Only PrimeReact allows to search components.
But PrimeFaces has sooo many components. It would realy help to port over the search-functionality provided by https://primefaces.org/primereact/showcase/

**Comment by melloware** [comment]
+1 I know my team of developers is so used to going to the showcase typing in the search of the component they are looking for when they look for examples.

**Comment by sqores** [comment]
@christophs78 @melloware An autocomplete menu will arrive before the new showcase is released. The dynamic menu I made yesterday was for this. It only takes some time as I am working on new components.

**Comment by melloware** [comment]
Awesome!

**Comment by christophs78** [comment]
glad to hear!

**Comment by sqores** [comment]
Finally closed with my last commit
