### ISSUE TITLE
Avatar: PrimeOne theme circle styling not applied

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces-showcase#269]
See screenshot. The `.ui-avatar-circle` is being overridden by the theme:
![image](https://user-images.githubusercontent.com/4399574/103459370-f614b380-4cdc-11eb-887d-83c0cc58a748.png)

**Comment by sqores** [comment]
There are some theme issues with new components and old chips component. A designer-jsf update is expected, which probably fixes these issues. I will look at it again if it has not fix after the theme update.

**Comment by melloware** [comment]
No problem I just wanted to track these issue so we could circle back and test them before final release.

**Comment by melloware** [comment]
This is fixed
