### ISSUE TITLE
PickList: PrimeOne search-icon hides actually clickable input

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces-showcase#273]
If you click in the middle into the filter input, the focus/cursor wont work as the icon overlays the input.
![picklist](https://user-images.githubusercontent.com/2485545/103533723-eab4ba00-4e8d-11eb-8141-f0e04e6fc995.png)

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primefaces/issues/6887
