### ISSUE TITLE
PickList: PrimeOne - transferAll shows all items before transfer is actual done

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces-showcase#274]
FireFox

![picklist2](https://user-images.githubusercontent.com/2485545/103536295-88aa8380-4e92-11eb-9843-594bcc907aff.png)

**Comment by mertsincan** [comment]
Interesting! Live showcase doesn't have this demo in picklist.xhtml. Therefore, I couldn't replicate it. @tandraschko Could you please check it again? If the problem persists, can you attach a code block for me?

**Comment by melloware** [comment]
I am not seeing this behavior either with the current picklist showcase example.

**Comment by tandraschko** [comment]
yep, seems to be fixed
