### ISSUE TITLE
Nova Light: Tabs

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces-showcase#301]
Looking at the Showcase in Nova Light the tabs are off:

![image](https://user-images.githubusercontent.com/4399574/105608242-d10de080-5d70-11eb-99da-6ead466418d8.png)

**Comment by mertsincan** [comment]
Hi @melloware,

These are legacy themes so we can make minor changes like this one, but overall, we can recommend users to use the new free PrimeOne themes.

**Comment by mertsincan** [comment]
I noticed that this is only in the documentation tabs so I don't think any fixes are needed. Thanks a lot for the report ;)
