### ISSUE TITLE
Wizard: missing from the new Showcase?

### ISSUE THREAD

**Issue by brooksie** [primefaces/primefaces-showcase#315]
There's no Wizard component in the new Showcase, although it does appear in the source code here:
https://github.com/primefaces/primefaces-showcase/blob/master/src/main/webapp/ui/panel/wizard.xhtml
Wizard isn't mentioned as being Deprecated in the doumentation, so I assume this is just a Showcase oversight? Thanks.

**Comment by sqores** [comment]
Thanks! added with https://github.com/primefaces/primefaces-showcase/commit/ec0c9c8101a938c1e78edd10206f9697f9b4e336

**Comment by brooksie** [comment]
Guys, I'm not sure if you are waiting for some release or other, but just to let you know I still don't see Wizard in the left hand menu in Showcase, nor can I find it through search. Many thanks.

**Comment by melloware** [comment]
Yes the latest showcase has not been pushed yet.
