### ISSUE TITLE
showcase primefaces 7 css doesn't work

### ISSUE THREAD

**Issue by fattanasio** [primefaces/primefaces-showcase#329]
Hi,
i imported maven project, cleaned, packaged and runned. 
It starts but doesn't work css and therefore you don't see the demo well.
Why ?
Thanks

**Comment by melloware** [comment]
so you checked out the project and ran `mvn clean jetty:run` ???

**Comment by fattanasio** [comment]
I had run the other commands:
mvn clean                 
mvn package              
mvn jetty:run  

I hadn't used the single command " mvn clean jetty:run".

Now it works, thanks
