### ISSUE TITLE
Datatable: column resize not working in Showcase?

### ISSUE THREAD

**Issue by brooksie** [primefaces/primefaces-showcase#331]
I don't seem to be able to get any of the 3 examples of column resizing to work in Showcase. 
I've tried with both Firefox and Chrome - same problem.
The column resize cursor never pops up to the left/right of the column header, so the width can't be altered.
NB. Not sure if this is a showcase-specific problem or more generic problem with PF10-RCx.

**Comment by melloware** [comment]
Fixed for 10.0.0 Final with this fix: https://github.com/primefaces/primefaces/issues/7057
