### ISSUE TITLE
Menu items not in alphabetical order

### ISSUE THREAD

**Issue by brooksie** [primefaces/primefaces-showcase#336]
This is trivial and cosmetic, I know, but the menus in Showcase are mostly in alphabetical order, except that M comes before O. 
Thanks.
![Screenshot 2021-03-23 123635](https://user-images.githubusercontent.com/4806551/112147821-09953380-8bd5-11eb-9858-c17917c3c10a.jpg)

**Comment by melloware** [comment]
Thanks for reporting
