### ISSUE TITLE
Showcase - component-search causes "View Expired"

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces-showcase#346]
Maybe we can do something (reload page??) to make this behaviour a bit more convinient.
It happens when you open the showcase once in a browser-tab and come back maybe a hour or two later.

![image](https://user-images.githubusercontent.com/10461942/112846941-de17ba80-90a6-11eb-892b-fc2cfd70fb97.png)

**Comment by christophs78** [comment]
Define something like
https://stackoverflow.com/questions/3642919/javax-faces-application-viewexpiredexception-view-could-not-be-restored
https://primefaces.github.io/primefaces/10_0_0/#/core/errorhandling

**Comment by sqores** [comment]
Closed https://github.com/primefaces/primefaces-showcase/commit/fe6dec208feb8bb89769f1b87b179a98501a793f
