### ISSUE TITLE
ProgressBarView : longRunning function is not called

### ISSUE THREAD

**Issue by ritonglue** [primefaces/primefaces-showcase#364]
The longRunning() function is not called (primefaces 8.0)

Moreover, getProgress2() should only return progress2 and not call updateProgress as it's the longRunning function that's responsible of incrementing progress2.

Finally, I think that the longRunning function should start a new Thread.

**Comment by melloware** [comment]
Are all these issues for the Showcase 8.0?  Because I am seeing `longRunning` is called in the 10.0 showcase?

We are not fixing old showcase issues its only there for people to reference.

**Comment by ritonglue** [comment]
I didn't test it in 10.0 but I'm pretty sure `longRunning` is not called in 10.0
Removing 'type="button"' solves the problem.
Please test-it.
