### ISSUE TITLE
AJAX: Include Dropdown Example In Menu

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces-showcase#367]
This example is not included in the Menu but a user just asked me about how to do this today and I sent them this link.

https://www.primefaces.org/showcase/ui/ajax/dropdown.xhtml

I think this should be in the Sidebar Menu of the showcase as its one of the most common use cases asked about.

**Comment by sqores** [comment]
Links as files that are not in the menu may have been forgotten. Since I have added them all one by one, there have been some overlooked ones. Those that were intentionally removed have already been commented out. I added it to 10, you can add to 11 @melloware .
